export const colors = {
    COLOR_PRIMARY: "green",
    COLOR_LIGHT: "#fff",
    COLOR_DARK: "#000",
    COLOR_DARK_ALT: "262626",
}

export const categories = [
    {
        id: "01",
        category: "Breakfast",
    },
    {
        id: "02",
        category: "Lunch",
    },
    {
        id: "03",
        category: "Dinner",
    },
    {
        id: "04",
        category: "Dessert",
    },
    {
        id: "05",
        category: "Snacks",
    },
];

export const recipeList = [
    {
        id: "02",
        name: "Akara and Bread",
        image: require("../assets/images/akara_and_bread2.jpg"),
        rating: "4.2",
        ingredients: ["2 cups of peeled beans", "1 medium onion", "2-3 fresh chili peppers (optional)",  "Salt to taste", "Vegetable oil for frying", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "darksalmon",
        description: "Akara is a popular Nigerian street food made from peeled beans, onions, and spices. It is deep-fried until golden brown and typically served as a snack or breakfast item.",
        steps: [
        "Soak the peeled beans in water for at least 3 hours or overnight to soften them",
        "Drain the soaked beans and blend them with the onion and chili peppers until smooth.",
        "Add salt to taste and mix well.",
        "Heat the vegetable oil in a deep frying pan. Scoop the bean batter using a spoon and carefully drop it into the hot oil.",
        "Fry the akara balls until they are golden brown and crispy on the outside, about 5-7 minutes.",
        "Remove the fried akara from the oil and drain on paper towels to remove excess oil.",
        "Serve the akara hot with bread, or as a standalone snack"
    ],
    },
    {
        id: "03",
        name: "Bread and Egg",
        image: require("../assets/images/bread_egg.jpg"),
        rating: "4.2",
        ingredients: ["Vegetable oil Or butter", "Bread",  "Eggs",  "Pepper",  "Onion",  "Maggi",  "Salt", "Tomatoes"],
        time: "20 mins",
        difficulty: "None",
        calories: "250 cal",
        color: "darkseagreen",
        description: "Bread and Egg is a simple and delicious breakfast dish made by frying eggs and serving them with bread",
        steps: [
        "Heat a frying pan over medium heat",
        "crack the eggs into a small bowl and beat them lightly with a fork or whisk",
        "Season with salt and pepper to taste.",
        "Once the pan is hot, add a small amount of butter or oil to coat the bottom of the pan.",
        "Pour the beaten eggs into the pan, tilting the pan slightly to spread them out evenly.",
        "Allow the eggs to cook ",
        "Using a spatula, gently lift the edges of the eggs and tilt the pan to allow any uncooked egg to flow underneath",
        "Once the eggs are cooked, remove them from the pan and place them on top of the bread slices",
        ],
    },
    {
        id: "04",
        name: "Garri and Groundnut",
        image: require("../assets/images/garri_groundnut.jpg"),
        rating: "4.2",
        ingredients: ["Garri" , "Groundnut", "Water", "Sugar or salt"],
        time: "2 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "darkolivegreen",
        description: "Garri and groundnut is a popular West African snack or meal made from cassava flakes (garri) and roasted peanuts (groundnut)",
        steps: [
        "Place the desired amount of garri in a bowl",
        "mix the groundnut with the garri in the bowl.",
        "Garri and groundnut can be served as is, or you can add sugar or salt to taste if desired",
        ],
    },
    {
        id: "14",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "400 cal",
        color: "forestgreen",
        description: "he savory flavors of sausages and chicken with the comforting crunch of toast",
        steps: [
        "Slice the cooked chicken breast into thin strips",
        "Heat a frying pan over medium heat and add the sausages. Cook them until they are browned and cooked through, about 8-10 minutes",
        "In the same frying pan, melt the butter over medium heat",
        "Place the slices of bread in the pan and toast them until they are golden brown on both sides, about 2-3 minutes per side",
        "Place the toasted bread slices on a plate",
        "Top each slice with a portion of the cooked chicken breast strips and a sausage",
        "Season with salt and pepper to taste."
        ],
    },
    {
        id: "06",
        name: "Indomie",
        image: require("../assets/images/indomie.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
        time: "20 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "mediumseagreen",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "07",
        name: "Moimoi and Pap",
        image: require("../assets/images/moimoi_and_pap.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "teal",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "08",
        name: "Pancakes",
        image: require("../assets/images/pancakes.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "cadetblue",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "09",
        name: "Pap and Akara",
        image: require("../assets/images/pap_and_akara2.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "paleturquoise",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "10",
        name: "Plantain and egg",
        image: require("../assets/images/plantain_and_egg.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "darkslateblue",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "11",
        name: "Yam and Egg",
        image: require("../assets/images/yam_and_egg.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "lavender",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "12",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "mediumpurple",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "13",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "rosybrown",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
//     {
//         id: "14",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans, Onion, Hot pepper,  Salt, Vegetable oil, Ground crayfish, Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal"
//     },
]